springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    urls[1]:
      name: Order Service
      url: /aggregate/order-service/v3/api-docs
    urls[2]:
      name: Inventory Service
      url: /aggregate/inventory-service/v3/api-docs
    urls[0]:
      name: Product Service
      url: /aggregate/product-service/v3/api-docs
    path: /swagger-ui.html


spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/spring-microservices-security-realm
server:
  port: '9000'